//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossoverShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string UserName { get; set; }
        public string OrderStatusCode { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> RepaidDate { get; set; }
        public Nullable<int> RepaidAmount { get; set; }
        public Nullable<System.DateTime> Cr_datetime { get; set; }
        public Nullable<System.DateTime> Mo_datetime { get; set; }
    }
}
