//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossoverShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Row_Id { get; set; }
        public int OrderId { get; set; }
        public int ProductID { get; set; }
        public int productQuantity { get; set; }
        public decimal productPrice { get; set; }
        public Nullable<System.DateTime> Cr_datetime { get; set; }
        public string BillingAddress { get; set; }
        public string DeliveryAddress { get; set; }
    }
}
