//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART_PAYMENT_DETAILS
    {
        public int CART_ID { get; set; }
        public int PAYMENTID { get; set; }
        public string PAYMENTSTATUS { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
