//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERDETAILS = new HashSet<ORDERDETAIL>();
        }
    
        public int ORDERID { get; set; }
        public string ORDERNUMBER { get; set; }
        public string INVOICENUMBER { get; set; }
        public int PAYMENTID { get; set; }
        public System.DateTime ORDERDATE { get; set; }
        public System.DateTime PAYMENTDATE { get; set; }
        public string SHIPPING_TRACKINGID { get; set; }
        public string ORDER_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILS { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual ORDERS_HISTORY ORDERS_HISTORY { get; set; }
        public virtual SHIPPING_TRACKING_DETAILS SHIPPING_TRACKING_DETAILS { get; set; }
    }
}
