//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYMENT()
        {
            this.CART_PAYMENT_DETAILS = new HashSet<CART_PAYMENT_DETAILS>();
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public int PaymentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PaymentStatus { get; set; }
        public string IsTransactionSuccessFul { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> Cr_datetime { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART_PAYMENT_DETAILS> CART_PAYMENT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
        public virtual User User { get; set; }
    }
}
