//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Category_BRANDS
    {
        public int BrandID { get; set; }
        public int ProductID { get; set; }
        public int CategoryId { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        public virtual Category_Master Category_Master { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
