//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTFEEDBACK
    {
        public int ProductFeedBackID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> UserID { get; set; }
        public decimal Rating { get; set; }
        public string Comments { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
