//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Segment_Master()
        {
            this.Category_Master = new HashSet<Category_Master>();
        }
    
        public int SegamentID { get; set; }
        public string SegmanetName { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> Cr_datetime { get; set; }
        public Nullable<System.DateTime> Mo_datetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Master> Category_Master { get; set; }
    }
}
