//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart_Item
    {
        public int Cart_Item_Id { get; set; }
        public int ProductID { get; set; }
        public int ProductQuantity { get; set; }
        public decimal CartItemCost { get; set; }
        public Nullable<System.DateTime> Cr_datetime { get; set; }
        public Nullable<System.DateTime> Mo_datetime { get; set; }
        public Nullable<int> Cart_Id { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
