//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashinexShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart()
        {
            this.CART_PAYMENT_DETAILS = new HashSet<CART_PAYMENT_DETAILS>();
            this.ShoppingCart_Item = new HashSet<ShoppingCart_Item>();
        }
    
        public int Cart_Id { get; set; }
        public Nullable<int> TotalItem { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<System.DateTime> Cr_datetime { get; set; }
        public Nullable<System.DateTime> Mo_datetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART_PAYMENT_DETAILS> CART_PAYMENT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_Item> ShoppingCart_Item { get; set; }
    }
}
